#pragma once

#include <Math/WindowsInstructions/__instructions.h>

BEGINNAMESPACE

DX_NAMEALIAS_PACKED(StoreByte2);
DX_NAMEALIAS_PACKED(StoreByte4);
DX_NAMEALIAS_PACKED(StoreByteN2);
DX_NAMEALIAS_PACKED(StoreByteN4);
DX_NAMEALIAS_PACKED(StoreColor);
DX_NAMEALIAS_PACKED(StoreDec4);
DX_NAMEALIAS_PACKED(StoreDecN4);
DX_NAMEALIAS(StoreFloat);
DX_NAMEALIAS(StoreFloat2);
DX_NAMEALIAS(StoreFloat2A);
DX_NAMEALIAS(StoreFloat3);
DX_NAMEALIAS(StoreFloat3A);
DX_NAMEALIAS_PACKED(StoreFloat3PK);
DX_NAMEALIAS_PACKED(StoreFloat3SE);
DX_NAMEALIAS(StoreFloat3x3);
DX_NAMEALIAS(StoreFloat4);
DX_NAMEALIAS(StoreFloat4A);
DX_NAMEALIAS(StoreFloat4x3);
DX_NAMEALIAS(StoreFloat4x3A);
DX_NAMEALIAS(StoreFloat4x4);
DX_NAMEALIAS(StoreFloat4x4A);
DX_NAMEALIAS_PACKED(StoreHalf2);
DX_NAMEALIAS_PACKED(StoreHalf4);
DX_NAMEALIAS(StoreInt2);
DX_NAMEALIAS(StoreInt2A);
DX_NAMEALIAS(StoreInt3);
DX_NAMEALIAS(StoreInt3A);
DX_NAMEALIAS(StoreInt4);
DX_NAMEALIAS(StoreInt4A);
DX_NAMEALIAS_PACKED(StoreShort2);
DX_NAMEALIAS_PACKED(StoreShort4);
DX_NAMEALIAS_PACKED(StoreShortN2);
DX_NAMEALIAS_PACKED(StoreShortN4);
DX_NAMEALIAS(StoreSInt2);
DX_NAMEALIAS(StoreSInt3);
DX_NAMEALIAS(StoreSInt4);
DX_NAMEALIAS_PACKED(StoreU555);
DX_NAMEALIAS_PACKED(StoreU565);
DX_NAMEALIAS_PACKED(StoreUByte2);
DX_NAMEALIAS_PACKED(StoreUByte4);
DX_NAMEALIAS_PACKED(StoreUByteN2);
DX_NAMEALIAS_PACKED(StoreUByteN4);
DX_NAMEALIAS_PACKED(StoreUDec4);
DX_NAMEALIAS_PACKED(StoreUDecN4);
DX_NAMEALIAS_PACKED(StoreUDecN4_XR);
DX_NAMEALIAS(StoreUInt2);
DX_NAMEALIAS(StoreUInt3);
DX_NAMEALIAS(StoreUInt4);
DX_NAMEALIAS_PACKED(StoreUNibble4);
DX_NAMEALIAS_PACKED(StoreUShort2);
DX_NAMEALIAS_PACKED(StoreUShort4);
DX_NAMEALIAS_PACKED(StoreUShortN2);
DX_NAMEALIAS_PACKED(StoreUShortN4);
DX_NAMEALIAS_PACKED(StoreXDec4);
DX_NAMEALIAS_PACKED(StoreXDecN4);

ENDNAMESPACE