#if OS_WINDOWS

#include <Math/WindowsInstructions/Instructions.h>

BEGINNAMESPACE

DX_IMPL_NAMEALIAS(VectorGetByIndex);
DX_IMPL_NAMEALIAS(VectorGetByIndexPtr);
DX_IMPL_NAMEALIAS(VectorGetIntByIndex);
DX_IMPL_NAMEALIAS(VectorGetIntByIndexPtr);
DX_IMPL_NAMEALIAS(VectorGetIntW);
DX_IMPL_NAMEALIAS(VectorGetIntWPtr);
DX_IMPL_NAMEALIAS(VectorGetIntX);
DX_IMPL_NAMEALIAS(VectorGetIntXPtr);
DX_IMPL_NAMEALIAS(VectorGetIntY);
DX_IMPL_NAMEALIAS(VectorGetIntYPtr);
DX_IMPL_NAMEALIAS(VectorGetIntZ);
DX_IMPL_NAMEALIAS(VectorGetIntZPtr);
DX_IMPL_NAMEALIAS(VectorGetW);
DX_IMPL_NAMEALIAS(VectorGetWPtr);
DX_IMPL_NAMEALIAS(VectorGetX);
DX_IMPL_NAMEALIAS(VectorGetXPtr);
DX_IMPL_NAMEALIAS(VectorGetY);
DX_IMPL_NAMEALIAS(VectorGetYPtr);
DX_IMPL_NAMEALIAS(VectorGetZ);
DX_IMPL_NAMEALIAS(VectorGetZPtr);
DX_IMPL_NAMEALIAS(VectorSetByIndex);
DX_IMPL_NAMEALIAS(VectorSetByIndexPtr);
DX_IMPL_NAMEALIAS(VectorSetIntByIndex);
DX_IMPL_NAMEALIAS(VectorSetIntByIndexPtr);
DX_IMPL_NAMEALIAS(VectorSetIntW);
DX_IMPL_NAMEALIAS(VectorSetIntWPtr);
DX_IMPL_NAMEALIAS(VectorSetIntX);
DX_IMPL_NAMEALIAS(VectorSetIntXPtr);
DX_IMPL_NAMEALIAS(VectorSetIntY);
DX_IMPL_NAMEALIAS(VectorSetIntYPtr);
DX_IMPL_NAMEALIAS(VectorSetIntZ);
DX_IMPL_NAMEALIAS(VectorSetIntZPtr);
DX_IMPL_NAMEALIAS(VectorSetW);
DX_IMPL_NAMEALIAS(VectorSetWPtr);
DX_IMPL_NAMEALIAS(VectorSetX);
DX_IMPL_NAMEALIAS(VectorSetXPtr);
DX_IMPL_NAMEALIAS(VectorSetY);
DX_IMPL_NAMEALIAS(VectorSetYPtr);
DX_IMPL_NAMEALIAS(VectorSetZ);
DX_IMPL_NAMEALIAS(VectorSetZPtr);

ENDNAMESPACE

#endif
