#if OS_WINDOWS

#include <Math/WindowsInstructions/Instructions.h>

BEGINNAMESPACE

DX_IMPL_NAMEALIAS_PACKED(LoadByte2);
DX_IMPL_NAMEALIAS_PACKED(LoadByte4);
DX_IMPL_NAMEALIAS_PACKED(LoadByteN2);
DX_IMPL_NAMEALIAS_PACKED(LoadByteN4);
DX_IMPL_NAMEALIAS_PACKED(LoadColor);
DX_IMPL_NAMEALIAS_PACKED(LoadDec4);
DX_IMPL_NAMEALIAS_PACKED(LoadDecN4);
DX_IMPL_NAMEALIAS(LoadFloat);
DX_IMPL_NAMEALIAS(LoadFloat2);
DX_IMPL_NAMEALIAS(LoadFloat2A);
DX_IMPL_NAMEALIAS(LoadFloat3);
DX_IMPL_NAMEALIAS(LoadFloat3A);
DX_IMPL_NAMEALIAS_PACKED(LoadFloat3PK);
DX_IMPL_NAMEALIAS_PACKED(LoadFloat3SE);
DX_IMPL_NAMEALIAS(LoadFloat3x3);
DX_IMPL_NAMEALIAS(LoadFloat4);
DX_IMPL_NAMEALIAS(LoadFloat4A);
DX_IMPL_NAMEALIAS(LoadFloat4x3);
DX_IMPL_NAMEALIAS(LoadFloat4x3A);
DX_IMPL_NAMEALIAS(LoadFloat4x4);
DX_IMPL_NAMEALIAS(LoadFloat4x4A);
DX_IMPL_NAMEALIAS_PACKED(LoadHalf2);
DX_IMPL_NAMEALIAS_PACKED(LoadHalf4);
DX_IMPL_NAMEALIAS(LoadInt2);
DX_IMPL_NAMEALIAS(LoadInt2A);
DX_IMPL_NAMEALIAS(LoadInt3);
DX_IMPL_NAMEALIAS(LoadInt3A);
DX_IMPL_NAMEALIAS(LoadInt4);
DX_IMPL_NAMEALIAS(LoadInt4A);
DX_IMPL_NAMEALIAS_PACKED(LoadShort2);
DX_IMPL_NAMEALIAS_PACKED(LoadShort4);
DX_IMPL_NAMEALIAS_PACKED(LoadShortN2);
DX_IMPL_NAMEALIAS_PACKED(LoadShortN4);
DX_IMPL_NAMEALIAS(LoadSInt2);
DX_IMPL_NAMEALIAS(LoadSInt3);
DX_IMPL_NAMEALIAS(LoadSInt4);
DX_IMPL_NAMEALIAS_PACKED(LoadU555);
DX_IMPL_NAMEALIAS_PACKED(LoadU565);
DX_IMPL_NAMEALIAS_PACKED(LoadUByte2);
DX_IMPL_NAMEALIAS_PACKED(LoadUByte4);
DX_IMPL_NAMEALIAS_PACKED(LoadUByteN2);
DX_IMPL_NAMEALIAS_PACKED(LoadUByteN4);
DX_IMPL_NAMEALIAS_PACKED(LoadUDec4);
DX_IMPL_NAMEALIAS_PACKED(LoadUDecN4);
DX_IMPL_NAMEALIAS_PACKED(LoadUDecN4_XR);
DX_IMPL_NAMEALIAS(LoadUInt2);
DX_IMPL_NAMEALIAS(LoadUInt3);
DX_IMPL_NAMEALIAS(LoadUInt4);
DX_IMPL_NAMEALIAS_PACKED(LoadUNibble4);
DX_IMPL_NAMEALIAS_PACKED(LoadUShort2);
DX_IMPL_NAMEALIAS_PACKED(LoadUShort4);
DX_IMPL_NAMEALIAS_PACKED(LoadUShortN2);
DX_IMPL_NAMEALIAS_PACKED(LoadUShortN4);
DX_IMPL_NAMEALIAS_PACKED(LoadXDec4);
DX_IMPL_NAMEALIAS_PACKED(LoadXDecN4);

ENDNAMESPACE

#endif
